const projects = [
  {
    title: "Close Encounters",
    description: "",
    technology:
      "JS / ES6 / HTML5 / CSS3 / Bootstrap / Node.js / Express / GraphQL / Mongo DB / Mongoose / Apollo / API / Leaflet / JWT / Heroku / Responsive Design /",
    technologyList: ["Javascript", "Express", "API", "Sequelize", "MySQL"],
    image: require("../src/images/closer-encounters-ss1.png"),
    demotype: "Live View",
    github: "https://github.com/DanielMrva/close_encounters",
    demo: "https://closer-encounters.herokuapp.com/",
    videolink: "",
  },
  {
    title: "Accretion (Concept App for USGS employee)",
    description: "",
    technology:
      "JS / ES6 / HTML5 / CSS3 / Bootstrap / Node.js / Express / MySQL / Sequelize / API / MVC-Handlebars / Heroku / Responsive Design /",
    technologyList: ["Javascript", "Express", "API", "Sequelize", "MySQL"],
    image: require("../src/images/accretion2.png"),
    demotype: "Live View",
    github: "https://github.com/AmberZimmerman/accretion",
    demo: "https://accretion2022.herokuapp.com/",
    videolink: "",
  },
  {
    title: "MOONR8KER",
    description:
      "MOONR8KER is an application that crosses somewhere between astrology and gravitational science. It will formulate an ideal activity for someone to take part in, relative to what phase the moon is in.",
    technology:
      "JS / ES6 / HTML5 / CSS3 / Materialize / API / Local Storage / Concept & Design /",
    technologyList: ["Javascript", "Express", "API", "Sequelize", "MySQL"],
    image: require("../src/images/moonraker-layout-landing-page-1.jpg"),
    demotype: "Live View",
    github: "https://github.com/AmberZimmerman/MOONR8KER",
    demo: "https://danielmrva.github.io/Lunar-Activities/",
    videolink: "",
  },
  {
    title: "Denver Harlequins Rugby Redesign (Coming Soon)",
    description: "",
    technology:
      "JS / ES6 / HTML5 / CSS3 / Strapi / Headless CMS / Node.js / React / Axios.js / Formik / Luxon / Next.js / Responsive Design /",
    technologyList: ["Javascript", "Express", "API", "Sequelize", "MySQL"],
    image: require("../src/images/rugby-website-wireframe.jpg"),
    demotype: "Coming Soon",
    github: "Coming Soon",
    demo: "",
    videolink: "",
  },
  {
    title: "On Second Thought (Backend Only)",
    description: "",
    technology:
      "JS / ES6 / HTML5 / CSS3 / Express / Node.js / API / MongoDB / Mongoose / MongoDB Compass / Insomnia",
    technologyList: ["Javascript", "Express", "API", "Sequelize", "MySQL"],
    image: require("../src/images/project-gifs/on-second-thought.gif"),
    demotype: "Video Walkthrough",
    github: "https://github.com/AmberZimmerman/on-second-thought",
    demo: "https://drive.google.com/file/d/133NcYuzGOFutr-_NW9NsUBHH87dIUvtK/view",
    videolink:
      "https://drive.google.com/file/d/133NcYuzGOFutr-_NW9NsUBHH87dIUvtK/view",
  },
  {
    title: "Categorizing Your Clique (Backend Only)",
    description:
      "This content management system allows the user to organize aspects of their business by viewing details about the departments, roles, and employees in the database.",
    technology: "JS / ES6 / HTML5 / CSS3 / CMS / Node.js / Inquirer / MySQL /",
    technologyList: ["Javascript", "CMS", "Node.js", "Inquirer", "MySQL"],
    image: require("../src/images/project-gifs/categorizing-your-clique.gif"),
    github: "https://github.com/AmberZimmerman/categorizing_your_clique",
    demotype: "Video Walkthrough",
    demo: "https://drive.google.com/file/d/14HoVuqsNcQepHpJSzImUIlFpxoWSUZb6/view?usp=sharing",
    videolink:
      "https://drive.google.com/file/d/14HoVuqsNcQepHpJSzImUIlFpxoWSUZb6/view?usp=sharing",
  },
  {
    title: "Stacking Your Squad",
    description: "Command-line application that helps a user to build a team",
    technology:
      "JS / ES6 / HTML5 / CSS3 / Bootstrap / Node.js / Inquirer / Jest / Command-line Application /",
    technologyList: [
      "Javascript",
      "HTML/CSS",
      "Command-line Application",
      "Node.js",
      "Inquirer",
      "Jest",
    ],
    image: require("../src/images/project-gifs/stacking-your-squad.gif"),
    github: "https://github.com/AmberZimmerman/stacking_your_squad",
    demotype: "Video Walkthrough",
    demo: "https://drive.google.com/file/d/1dkVYjO1oYt4Z6aMn3xa9273rPobtBAv-/view?usp=sharing",
    videolink:
      "https://drive.google.com/file/d/1dkVYjO1oYt4Z6aMn3xa9273rPobtBAv-/view?usp=sharing",
  },
  {
    title: "Ecommerce Everything Pencils (Backend Only)",
    description:
      "The is the backend component to a ecommerce site for an online retail store. It meets MVP criteria. An Express.js API was built to use Sequelize to interact with a MySQL database.",
    technology:
      "JS / ES6 / HTML5 / CSS3 / Express / Node.js / API / Sequelize / MySQL / Insomnia /",
    technologyList: ["Javascript", "Express", "API", "Sequelize", "MySQL"],
    image: require("../src/images/project-gifs/ecommerce-everything-pencils.gif"),
    github: "https://github.com/AmberZimmerman/ecommerce-everything-pencils",
    demotype: "Video Walkthrough",
    demo: "https://drive.google.com/drive/folders/1aPcGE6_DMf_JfofeDzrjpkjgzBzFul_Q?usp=sharing",
    videolink:
      "https://drive.google.com/drive/folders/1aPcGE6_DMf_JfofeDzrjpkjgzBzFul_Q?usp=sharing",
  },
  {
    title: "Fussy Flamingo",
    description:
      "A silly little quiz about flamingos using vanilla javascript and html/css. Keeps track of scores and lets users save them in local storage.",
    technology: "JS / ES6 / HTML5 / CSS3 / Local Storage / IndexedDB /",
    technologyList: ["Javascript", "HTML/CSS", "Local Storage"],
    image: require("../src/images/fussy-flamingos-ss1.png"),
    github: "https://github.com/AmberZimmerman/fussy-flamingos-timed-quiz",
    demotype: "Live View",
    demo: "https://amberzimmerman.github.io/fussy-flamingos-timed-quiz/",
    videolink: "",
  },
  {
    title: "Just Another Text Editor",
    description: "",
    technology: "JS / ES6 / HTML5 / CSS3 / PWA / Workbox /Webpack /",
    technologyList: [""],
    image: require("../src/images/jate-installed-desktop-ss1.png"),
    github: "https://github.com/AmberZimmerman/text-editor",
    demotype: "Live View",
    demo: "https://thegreatjate.herokuapp.com/",
    videolink: "",
  },
  {
    title: "Dolly Work Day Planner",
    description:
      "A Dolly Parton themed day planner that allows a user to schedule in hourly tasks. Hourly tasks will change background color in real time. Tasks can be saved to local storage.",
    technology:
      "JS / ES6 / HTML5 / CSS3 / Local Storage / IndexedDB / Moment.js /",
    technologyList: ["Javascript", "HTML/CSS", "Local Storage", "Moment.js"],
    image: require("../src/images/dolly-work-day-planner-ss4.png"),
    github: "https://github.com/AmberZimmerman/dolly-workday-planner",
    demotype: "Live View",
    demo: "https://github.com/AmberZimmerman/dolly-workday-planner",
    videolink: "",
  },
  // {
  //   title: "Ambers Magical Weather App",
  //   description: "",
  //   technologyList: ["Javascript", "HTML/CSS", "API", "Local Storage", "Bootstrap"],
  //   image: require(""),
  //   demogif: "",
  //   github: "https://github.com/AmberZimmerman/ambers-magical-weather-app",
  //   demo: "https://amberzimmerman.github.io/ambers-magical-weather-app/",
  //   videolink: "",
  // },
  {
    title: "Never Miss A Note",
    description:
      "This app allows a user to write, save, and delete notes. Begin by selecting the new note and then typing a title then a description below. Once finished the user can click the floppy disk to save the note.",
    technology: "JS / ES6 / HTML5 / CSS3 / Bootstrap / Node.js / Express /",
    technologyList: [
      "Javascript",
      "HTML/CSS",
      "Bootstrap",
      "Node.js",
      "Express",
    ],
    image: require("../src/images/never-miss-a-note-ss1.png"),
    github: "https://github.com/AmberZimmerman/never_miss_a_note",
    demotype: "Live View",
    demo: "https://never-miss-a-note.herokuapp.com/",
    videolink: "",
  },
  {
    title: "Personal Readme Generator",
    description: "",
    technology: "JS / ES6 / Inquirer / Node.js / Generate Markdown /",
    technologyList: [""],
    image: require("../src/images/personal-readme-maker-ss1.png"),
    github: "https://github.com/AmberZimmerman/ambers_easy_readme_maker",
    demotype: "Video Walkthrough",
    demo: "https://www.youtube.com/watch?v=dgG3QxZduiQ",
    videolink: "https://www.youtube.com/watch?v=dgG3QxZduiQ",
  },
  // {
  //   title: "Final project",
  //   description: "",
  //   technologyList: ["Javascript", "Express", "API", "Sequelize", "MySQL"],
  //   image: "",
  //   demogif: "",
  //   github: "",
  //   demo: "",
  //   videolink: "",
  // },
  {
    title: "Regex Tutorial",
    description: "",
    technology: "Regex / Github Gist / Tutorial Writing /",
    technologyList: [""],
    image: require("../src/images/regex-tutorial-ss1.png"),
    github: "",
    demotype: "Gist Post",
    demo: "https://gist.github.com/AmberZimmerman/e17f3e30de5e28adddaae7c63892884f",
    videolink: "",
  },
  {
    title: "Secure Password Generator",
    description:
      "User can generate their own secure password by choosing specific criteria based on given options. ",
    technology: "JS / ES6 / HTML5 / CSS3 / Responsive Design /",
    technologyList: ["Javascript", "HTML/CSS"],
    image: require("../src/images/generated-password-ss1.png"),
    demotype: "Live View",
    github: "https://github.com/AmberZimmerman/secure-password-generator",
    demo: "https://amberzimmerman.github.io/secure-password-generator/",
    videolink: "",
  },
];

export default projects;
